version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
    - echo Running JUNIT TEST CASES
    - mvn clean test 
       
reports:
  arn:aws:codebuild:ap-south-1:481782230560:report-group/Hello-world:
    files:
      - "**/*"
    discard-paths: yes
    
